#索引统计相关配置
es.metrics.cluster.buckets.max.num: 5000
es.metrics.nodes.buckets.max.num: 5000
es.metrics.indices.buckets.max.num: 10000

#DSL查询模版相关配置
# 默认的查询限流值
default.query.limit: 800
# 查询模板过期删除时间
delete.expired.template.time: now-1d
# 查询历史数据时间
history.query.time: now-93d

#admin相关配置
admin.port.web: 8010
admin.contextPath: /admin/api
admin.url.console: http://10.190.6.107/
admin.url.kibana: http://10.160.80.135:8061/
admin.thread.size.op: 20

#gateway相关配置
es.gateway.url: 10.190.44.150,10.190.42.122
es.gateway.port: 8200
es.user: 1
es.password: 
scroll.timeout: 60s

#ES元数据集群相关配置
es.update.cluster.name: logi-elasticsearch-7.6.0

#ES客户端相关配置
es.client.cluster.port: 8061
es.client.io.thread.count: 8

#可观测性相关配置
monitorJob.threadPool.initsize: 20
monitorJob.threadPool.maxsize: 20

#扩展服务相关配置
extend.service:
extend.fileStorage: s3
extend.employee: defaultEmployee
extend.loginProtocol: defaultLogin

#dcdr相关配置
# 并发执行数
dcdr.concurrent: 2
# 容错数
dcdr.fault.tolerant: 5

#依赖的 remote 接口的配置
#zeus的相关信息
zeus.server: 10.96.65.64:8010 #0.3.2修改
zeus.token: 9e2dbb6e5b1e594d1820e0f21669b240 #0.3.2修改
zeus.templateId: 3
zeus.user: root
zeus.batch: 2
zeus.timeOut: 300
zeus.tolerance: 0
zeus.grpId: 3 #0.3.2新增
#s3的相关配置
s3.endpoint: s3-gzpu-inter.didistatic.com
s3.access-key: 
s3.secret-key: 
s3.bucket: logi-data-es
#swagger
swagger.enable: true

#集成测试相关配置
integrate.test.admin.ip: 127.0.0.1
integrate.test.admin.port: 8010
integrate.test.es.ip: 10.190.55.161
integrate.test.es.port: 8888
integrate.test.esuser: 1
integrate.test.operator: admin

#统计项目对应各方法代码行相关配置
stat.method.line.standardLineOfMethod: 60

#日志相关配置
logging.pattern.file: "[%level][%d{yyyy-MM-dd'T'HH:mm:ss.SSS}][%t] %msg%xEx%n"
logging.config: classpath:log4j2-test.xml
logging.path: .
logging.file.max-history: 5

#spring公共配置
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
  profiles:
    active: test
  datasource:
    name: data
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://127.0.0.1:4859/es_manager_test?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&allowMultiQueries=true&useSSL=false&alwaysAutoGeneratedKeys=true&serverTimezone=GMT%2B8
      username: root
      password: 
      initialSize: 10
      validationQueryTimeout: 5000
      transactionQueryTimeout: 60000
      minIdle: 10
      maxActive: 30
      max-wait: 60000
      keepAlive: true
      time-between-eviction-runs-millis: 1000
      min-evictable-idle-time-millis: 300000
      defaultAutoCommit: true
      validationQuery: select 'x'
      testWhileIdle: true
      testOnReturn: false
      testOnBorrow: true
      logAbandoned: true
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      filters: stat,wall
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB
  logi-job:
    driver-class-name: ${spring.datasource.druid.driver-class-name}
    jdbc-url: ${spring.datasource.druid.url}
    password: ${spring.datasource.druid.password}
    username: ${spring.datasource.druid.username}
    max-lifetime: 60000
    init-sql: true
    init-thread-num: 50
    max-thread-num: 100
    log-expire: 3 # 日志保存天数，以天为单位
    app_name: arius_test03
    claim-strategy: com.didiglobal.knowframework.job.core.consensual.RandomConsensual
    node-name: node1
    job-log-fetcher-extend-bean-name: com.didiglobal.knowframework.job.extend.impl.DefaultJobLogFetcherExtendImpl
    elasticsearch-address: 10.96.75.19
    elasticsearch-port: 19578
    elasticsearch-user:
    elasticsearch-password:
    elasticsearch-index-name: index_observability
    elasticsearch-type-name: _doc
  kf-security:
    app-name: know_search
    driver-class-name: ${spring.datasource.druid.driver-class-name}
    jdbc-url: ${spring.datasource.druid.url}
    password: ${spring.datasource.druid.password}
    username: ${spring.datasource.druid.username}
    resource-extend-bean-name: resourceExtendManager
    #    0.3.1.1新增
    login-extend-bean-name: logiSecurityDefaultLoginExtendImpl
#  op-manager配置
  op-manager:
    data-source-name: logi-op-manager
    driver-class-name: ${spring.datasource.druid.driver-class-name}
    url: ${spring.datasource.druid.url}
    username: ${spring.datasource.druid.username}
    password: ${spring.datasource.druid.password}
    max-wait: 60000
    time-between-eviction-runs-millis: 1000
    min-evictable-idle-time-millis: 300000
    validationQuery: select 'x'
    pool-prepared-statements: true
    max-open-prepared-statements: 50
    filters: stat,wall
    validation-query-timeout: 5000
    transaction-query-timeout: 60000
    max-active: 30
    keep-alive: true
    default-auto-commit: true
    test-while-idle: true
    test-on-return: false
    test-on-borrow: true
    log-abandoned: true
    initial-size: 10
    min-idle: 10
  application:
    admin:
      enabled:
  transaction:
    default-timeout: 60
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
