export const cachePage = [
  "/cluster/physics",
  "/cluster/logic",
  "/cluster/edition",
  "/index-tpl/management",
  "/index-tpl/create",
  "/index-tpl/service",
  "/index-admin/management",
  "/index-admin/service",
  "/search-query/index-search",
  "/search-query/dsl-tpl",
  "/indicators/cluster",
  "/indicators/gateway",
  "/work-order/my-application",
  "/work-order/my-approval",
  "/work-order/task",
  "/scheduling/task",
  "/scheduling/log",
  "/system/config",
  "/system/operation",
];
export const mulityPage = {
  "/cluster/logic/detail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/cluster/physics/detail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/index-tpl/service/detail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/index-admin/management/detail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/index-tpl/management/detail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/work-order/my-approval/detail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/work-order/my-application/detail": (lan: string) =>
    decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/work-order/task/detail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
  "/work-order/task/dcdrdetail": (lan: string) => decodeURIComponent(window.location.search.slice(1).split("&")[0].split("=")[1]) + lan,
};
