export default {
  SET_LOADING: 'SET_LOADING',

  // 侧边栏是否收起展开
  SET_SLIDER_MENU: "SET_SLIDER_MENU",

  //
  SET_USER: 'SET_USER',
  SET_MODAL_ID: 'SET_MODAL_ID',
  SET_DRAWER_ID: 'SET_DRAWER_ID',
  SET_CLUSTER_COST: 'SET_CLUSTER_COST', // 设置集群成本
  SET_CLUSTER_NODE_LIST: 'SET_CLUSTER_NODE_LIST',// 节点列表
  SET_CLUSTER_PACKEAGE: 'SET_CLUSTER_PACKEAGE',// 版本列表

  // 开启关闭全屏
  SET_FULL_SCREEN_CONTENT: 'SET_FULL_SCREEN_CONTENT',

  SET_APP_LIST: 'SET_APP_LIST', // 设置项目列表
  SET_APP_SPIN: 'SET_APP_SPIN', // 设置app列表spin
  SET_PAGINATION: 'SET_PAGINATION', // 分页
  SET_APP_SUB_VALUE: 'SET_SUB_VALUE', // 存储项目管理查询表单VALUE

  //权限点action
  SET_PERMISSION_POINTS: 'SET_PERMISSION_POINTS',

  // region
  SET_PHY_CLUSTER_LIST: 'SET_PHY_CLUSTER_LIST',
  SET_REGION_LIST: 'SET_REGION_LIST',
  SET_RACKS: 'SET_RACKS',
  SET_RACKS_ARR: 'SET_RACKS_ARR',

  // 物理集群配置信息
  SET_PHY_CLUSTER_CONFIG: 'SET_PHY_CLUSTER_CONFIG',
  SET_PHY_CLUSTER_CONFIG_LIST: 'SET_PHY_CLUSTER_CONFIG_LIST',
  SET_PHY_CLUSTER_CONFIG_ROLES: 'SET_PHY_CLUSTER_CONFIG_ROLES',


  // 创建索引
  SET_INDEX_CREATE_TEMPORAYFORMMAP: 'SET_INDEX_CREATE_TEMPORAYFORMMAP',
  SET_CURRENT_STEP: 'SET_CURRENT_STEP',
  SET_FIELD_TYPE_MAP: 'SET_FIELD_TYPE_MAP',
  SET_THIRD_CHILD_MAP: 'SET_THIRD_CHILD_MAP',
  SET_INDEX_CREATE_LOADING_MAP: 'SET_INDEX_CREATE_LOADING_MAP',
  SET_INDEX_CREATE_SECOND_CHILD_MAP: 'SET_INDEX_CREATE_SECOND_CHILD_MAP',
  SET_EDITOR_INSTANCE: 'SET_EDITOR_INSTANCE',
  SET_CLEAR_CREATE_INDEX: 'SET_CLEAR_CREATE_INDEX',

  // task // dcdrStepDetail
  SET_DCDR_STEP_DEL: 'SET_DCDR_STEP_DEL',
  SET_TASK_BASE_INFO: 'SET_TASK_BASE_INFO',
  SET_TASK_MENU: 'SET_TASK_MENU',
  SET_TASK_BASE_LOADING: 'SET_TASK_BASE_LOADING',

  // 集群看板
  SET_CLUSTER_NAME_TIME: "SET_CLUSTER_NAME_TIME",
  SET_CLUSTER_IS_UPDATE: "SET_CLUSTER_IS_UPDATE",

  // Gateway 看板
  SET_GATEWAY_TIME: "SET_GATEWAY_TIME",
  SET_GATEWAY_IS_UPDATE: "SET_GATEWAY__IS_UPDATE"
};